---
name: Synchronize upstream (Cron) for pre-commit-hooks
on:
  workflow_dispatch:
  schedule:
    # Run this Action every 7 days at 0:00pm UTC
    - cron: "0 0 */7 * *"

jobs:
  sync-upstream:
    strategy:
      matrix:
        target:
          - pilots
          - chaotic
          - home-manager
          - sops-nix
          - nixpkgs-wayland,
          - neovim-nightly-overlay
          - impermanence
          - pre-commit-hooks
          - microvm
          - nix-fast-build
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Auth Token
        # https://github.com/tibdex/github-app-token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - uses: actions/checkout@main
        with:
          ref: master
          # submodules: true
          token: "${{ secrets.ACCESS_TOKEN }}"

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "chore(flake) update flake.lock for inputs.${{ matrix.target }}"
          pr-labels: |
            flake-lock
            automated
          inputs: ${{ matrix.target }}
          token: ${{ steps.generate_token.outputs.token }}
