---
name: Synchronize upstream (Cron)
on:
  workflow_dispatch:
  schedule:
    # Run this Action every 7 days at 0:00pm UTC
    - cron: "0 0 */7 * *"

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Auth Token
        # https://github.com/tibdex/github-app-token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - uses: actions/checkout@main
        with:
          ref: master
          # submodules: true
          token: "${{ secrets.ACCESS_TOKEN }}"

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "chore(flake) update flake.lock"
          pr-labels: |
            flake-lock
            automated
          inputs: nixpkgs-wayland sops-nix pilots chaotic neovim-nightly-overlay microvm pre-commit-hooks impermanence nix-fast-build
          token: ${{ steps.generate_token.outputs.token }}
