minio:
    host: ENC[AES256_GCM,data:WfLFg57yJTzX8fLZb5Vusbxj//ea+Ng=,iv:DEZKaUx7irCFTRLI8Y1i/pWxMitvOFbs7y/InGCJ6cM=,tag:OXBA+11vs1KlWR8czAOPGg==,type:str]
    accessKey: ENC[AES256_GCM,data:3jkfqyAhFtbawZK6i8JZU2lp13M=,iv:boM5mvwEMb/s/j6qQkQnRDbL7hCZJd4FCyO1EuIbOCw=,tag:jMLGDhqOcuPwDcv2F9y8vg==,type:str]
    secretKey: ENC[AES256_GCM,data:0PEsCvOEgZvN4IijfKCi7h9bAU5FhIazZ85P52xEr+et41c+ubKh4Q==,iv:UQDFtNHh/gxDTvCm1xV99BH5JDM1T3r/9TZmnahI6fI=,tag:xcAEfxHZQ0dmjC6NzEg4DQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z3sn5lc7dn4cwwar29dy7yl9zqqygdunds42nw8rm9lh5adgyu3s2ll05r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZEpXdXc0UGxaR29LVko2
            ZjhQbEFYSFA3RTB1M01OcWNEZTA3QlBzSkdRClQrMEpyaHJvemM1UGVXV2RreHhM
            TWhRR1F0R3pNN2FjaHJWWUg3akN6MFUKLS0tIEdHTkhmL0VrT3laSnNJS3A3N1Bu
            cWlOSE5icVJZU3BUT1V3L05wOXNkWUUKoZ7TwBY8jTq+IBKXwoZMyXBjZbUb//+s
            IhJuuOzVvdgTKOOaXeFRB4OEonMEAP/O+3FE7VZoC4xq8KcHNJbZYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-08T10:18:34Z"
    mac: ENC[AES256_GCM,data:iwGq8YlsGl3l17pig2DrUQrjKM/M1O1DJQzFAfMfb0yODpHcaus3gKLK9QP/1yjOhLFsuddjlq+wlTClqdB8tW3wmZ3c0MNfU8qyLeyOTQVr00/498aPttci4GeDgDkq/rGriUiDFhmNy/uzeMOTTqBGTBbxg7khkLG+gKGoQMA=,iv:8BrCsYGoIB2WolzCIT414mJLrpEIBpIpzJLSfn95xGs=,tag:Dki1+1947+ZZ7t0lrO56Cg==,type:str]
    pgp:
        - created_at: "2024-02-08T10:18:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAzVskl6rsqh0ARAArsw/k9sgkLBtVzvH3nU4bbCCeZZyAqfZRtxbXclN6n3a
            Uw+owI7G+3B4Jb9J+904PY1pYj+R2cqmEKRWcrmbT+HQ31dNUefrAbWy2zSElzEt
            vASHnKfKE0CGLCSWGheNYCvG99r1xEtUsojSceWHi1TNm1WWGs8EV7xXyG/EkZaf
            xIril2jZoIkfOtic5Ps1t88IOPkkz2XUPHRpJtnD0Od95fizeyiE//Kb0W44nyEK
            5vsLz8C9zsGjBV1uclayJAtCVswffj3ikehug6NKgAq2KV98c2a6EfZRS3OTY/XL
            vN9g/hwYi6Rxt9b8jXybbiqt2ZIuz+2SVXWwtYtbSWxeiFzrD6F5IZP/Yhw5YM+H
            AJ8ZtSV95HSos5i7p1Cxj3714tHMaYYwtScBErxHMxNKZimycc5/yWAzIGptWKLU
            wZDWa6lawB3m1hlG+RKPnfh7qHY9weMxjYw65uzWRB+Hs0PM2DaijDaN7Tdi/7tU
            Smui3rSoQ0zpQKowCajpgGmhU8vipjbnuYX/m9g5Lp/3dzCm9H58dSGBo1q5wGyz
            p3AGgsijNqnaQsC4rFMHF3lVnclldqfM/UTXpNWOMHr/gTCG/zhOCSeSdveN8QJB
            5Z8QD3ttTrFOzbXASPJZVNP4d9mXTTSPYbYUUmE5pe8qPWWtD5S2LN44RB1W68vS
            XgH2LTyzYsPU3EK5dVXBcT+l2JoJmqFCVc7bhArpbx82xaXY5WLjKU5rk/I7rCxK
            588HHo0Tcu0I3yj9U2U20LEfwCmtLlur0hykuZRgO7+ZdiDAHpdPf0i4Uk2E610=
            =4w4r
            -----END PGP MESSAGE-----
          fp: B08FE2644F9FC450AF425FF5B94F394B72884017
        - created_at: "2024-02-08T10:18:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0Q28yf+m+BrAQ/+LAzfonF0x46ag4elmaaTAVHmyWJ2tmJzvM4ZVx/r5UHV
            ZOmOJK5l5fkH39Errw7n0NRvPbyNkA6d8xFTU+SeR6nciJ3CeNscmVWu7xFfw/Tu
            2zt7AKidmrWUNsptvWpN6Rmi62sHnarUioD6qZUt1kSyxolCFJ6MDat/tLywIYmw
            scWVUO3m3RmFaOqaabR0eajgypVxzk+pVpv+l/hymsCwvtYxXA7cHBNKh3UXNuck
            4soxhpmX4zB051EUs06VVxmUiiaIgoACHlr1sp6xv5/HjW/o1ylMfPV2jqhtfUt+
            F4Cl7jNetF6yQfkz/c31zn9MU+umUAa7OYKaUwILz0bTJ7dPyES1N261q7CBrehh
            yKPSidBNzWJvX4M4FbPNwlObDIoYfY5lSBfcP4+RNoAZuplGJdmO2H0sLx2iIPls
            zGdITmC4+oBREyxVnfgHJsaeDk7OxsUypdI7Sv6m+OJZe6AFwCRYPDSaCnhK4lNC
            vLlmEsiDqRclFdZm+NzICJ762xAydPPU03UYdkCgzgFqc8FT3/8P6Hk7lIfnW9Bn
            t71y16gy2V58vH5svRsrYM4sXEYBshfARhJnVWn26UOwdg8iJD6s7XLS/EDtKWtp
            Dw1ALNDukWipHcpME1fSeiUb3QIDHSOpKFkTZvWGDys3VqCFN4/TRMP7OjRitrOF
            AgwDlo4O5o7M6KgBD/4xqnCkpONwBomj7D89uC3PrCt2KB8H5yHOd+Lj15aa9W2z
            UWDSzMAJogmm3Yi8uZQqYVEl5HRYLK3ezDpvdypsexweFMsuq8Sd7KDon6kEg6l0
            KdYz6/O9cHwY8FFfWxgC/z3HwrFuo0nebL9IzNU49wjAry+FBxIsDOMZx1nUtUTU
            b0iI2DmJJ2EWgpYQY4ZqQvpqtFcD1XEwnUQl9PKPchUn2mGNmAOgDirGozFOTUWA
            n+xtBqhqSDfuHgBGOCqVSXQhEWSCe9KgSDFbDPTsXc0wUmnTbP597LzLk+V9k3TI
            c4JpJGaNYONZYjWnq6tD4+JUYlOmTQOoidr+pjbQj/8WwhEeMFCAtVwXZcR95jsB
            yDUmBItbO/3fGqvhlj1SDu08ZWLxEE9YNlXRRqJHnQx9EnbDz60TOG2Y7pao7+rn
            aBKkyVOdpfpsjtdubI63JCJ3r4NJ7VdtbIBN6pLqPGUFA2ZTlu9Svm2hRz4mlz2r
            r0TGntyRxBh78ftX1QE2K9+8WEyB2D6NOpv1u9059P8qkccQUSitorVlir9nDys+
            I8l5utLEbTBT8z9yXcECahYQG2I25uukvbHSVrmKbZ8GJDSTbLK+9P8sFWfVyt9w
            BIQdkrqwcZBWRjZ+9qxQk/5pV8JeN59ALpoEzC98lVkmcEdoM7/d9Su6gtUZZ9Ro
            AQkCEFtGtln+XVrnraWO1TjmS/qh+mKft9LhFjJbkjov5htUhG8PvANPzamojHcZ
            +NgloAvqOKUQh0v/I6fbbK0zrc+sN1C1s670cBk0NAR9ptReO/9yuk4mSHD6+bRh
            qrYeMeRelAA=
            =PNqv
            -----END PGP MESSAGE-----
          fp: 5825C9F026638FF69FDC278DEA5A11F2DDC77EF1
    unencrypted_suffix: _unencrypted
    version: 3.8.1
