gitconfig:
    general: ENC[AES256_GCM,data:6rVg1zh9C3B/bISAVXZ5MUL1cQxgUPHzaze7GoIMJ9sk7+9BqF/9MJ+UU647WxhiZdlkmnEs9LEX8mSp4xKb7s0WHncXHD3w1NDEqTx4+ARqrgNIdY6/5HnQLTU7LRKn1VBsOIpn5MG0zRHgpE2UkpqhSXugKiBtkp1UTZDffkjkAK8noDsw5GtEUwl2I9eGFUKxbhCZ3SqsCUVdM80RJD8YvOST79MfyDL/lhk/ZhrAx8NXdC3o8y4NA1ATuvZDiHfbKyfk1CAJSKR0qPpOviCkT0RPx29tL637pldvVayp8ffE9xcpeShfEEDFfm8fFm9PzWlCA9fCxNt4LV3oEcE9UFTx7CwrPTGhx1LphfISu0PLbsIAQy0rS3gzaFZaKkMuFQX26XPVYl5hJO3T53F4ihDe12ecWVfxyy+tTt/IaTUP8DPpiylRPG8jqWBCoEPLKMk73sYnx1oVzm5t6WsqYUoZL4XgpjBhVMkYp31T9/viV75DQ+uabmxKlz1YA3zveqWxUZg8HCVH4u1fBj12gAbaHLgUWWWRRaU7DTxQhX2HHGydhqXz7TzUGLwtPC5H/nU2QOUrckXCDA33F5f7I0YyAaweh0UVtTKvHeCT1BYATLgjfA1DUEbDXsxLc8Fm1h6DuMveE+vTEyaj/Eljy2/zTQhWtl4FRQEj86wL9LUeQQstfYeUUBfmNPZox49snTSaEaLo3w3GkqB/G0P37wMx2aW0y3n9a9NAiBr3GO0ZVhmVRvN4R/QRx6HIrYb9vExVnHQ61uGc94jcy+VN+YNuLGoXUxCYVc1B/Jfo/YWicRwbvcqrbnvbBDah0nePeuVS7j8LxynWC019LBFg7pjgRiRMay5l01bITG7zUTnipPGIQsCPkNbk9Vc0veX4x4i63AOpPCm3sEKbTOap/GGvAIlQ7qoL71OZUWAxC05qiU/OdI513rhRKpdMgLKkGV/CjmQBcQQOgdMeLTDP5jKjMo0+UYDSmmWG6HDwFlR0eDCS7yAk9XvtczgH2Ntn2p+avZQ5i14wwbfxgPxYKrwrA0Tr5MkV6f4ftZkjXfuVlL2Vy3RtSB/TqEeOqBt84afUDp9ZEU6VklqvUrWyLhbKarq0b+V18yH3Bp57HfI+NtINjN6DIZ+1ynFFQDWhMqmnm8Km0LFOtwEzUTxg201lcPBoVeyvQ5l4HNcvRoJOw42lUmBVkiirfkwhm76z85jrb5QMSProl1uvbSziCliXZUhn5ySwDssfe2qA2mme2bUZyWzADllWrN06MyYdzK05YtaJQsEf95Cr/ncpnIABDhqbBFLDNDqGIZjBGlFHZ4K+FktLT28qZXd8TZqxS3brBVOPImYXgv8UEPcfisJfDrL16A00KzFSDvAFafPiQ78xsqQDSb5vsjhqyu3SERSNZa81FZZp7lffgCyoTOevN4d0jd5rbPPe5raIPDLfAeFeUe8RzMHQ+ekApql/R54qjvzTDSgOHlinVeAXKPHXnpHS/eJlSG+LqnwlPTonbMI0aC6DQzdeLA4SIkN5pxGEXzNnUVYpO3yPsu2TWmsQe5BFvjhIIvD31vXQw4PZ348DXt3WmAPNoz9FtDR4jqknKLz1Pz8jh3youohIM3g12kRz6B1cg53jBMnFfD8syWNOmXL/r+X+lBqcYX4ya/o3cSnYCHuL79vI4zue11qX3n11sXX5FhUdSQNEgyMBC6/6HOOJzuRSPLYnpV2uj8M6gEKQJmAIDP13+aQQicd6R6Qrh/MKr8euYLMoje5MPKZXlIf+29f7D6jV94EKJY+LNKy54iq1tksw9NaWQPa1CxSlnZHXz/C7rGMP9+ZcxPNY93OLyH1sU6PHxivp6p5XhfVdjmi6FY2tTHM/UbjSa4kSsTDpZnafT/9ylLl1rq8Nww1R3HlNV3OtTY+wNUyICZNC4K+6pmoYQNbJdg81jrYekC0fKaqhbd9DI5wlDoG2WobyUWWMKgltOdSGJtTRLHsA6j+T0ZjNSz81ItrfhZ9afR0/rt3VI0I9jRJEuduFhygaeG5Py/mrMSJlQYNo/P7qXmy3SmsdqiFtB/5/G2PKxnQaCY1RuIP3fQspZm3Ug5jLNVVLVECwOx9xacTX+B5Lqi17VBFkb7S5gVCGO5qQqJXb8O24p//BkYTwPhia5pK2oBZfmMrZUs6BVKmCGvC1s4AExcsJ9DSRwgRsxJ9EHSGvUEvlInmFJqOm7kvlYQzO+KdweV0SldgK+y+vKAmmLlQekAqKAMLMeqw1SJFEknTTwWjAdAEal3shDBt+iUUX54yguQ==,iv:sFzyeU6segVgKPmjGkAGR5jgsF8VSL5ScKfxEIe1Grw=,tag:eV1ATVx+JNn9HtX5TPXkww==,type:str]
    profile:
        personal: ENC[AES256_GCM,data:1nLs5S2ZZIwdwc5gvt114hVfYX4VoGxFP5x5E39b410ZTrqtCXgY3gWwU55vh16aqj7P1tOSG5n2goGM0wLjUZ7+kc9S1gE8u2PiHTGOMIqsQJHDWFRbQGSUIFdow8RaiJQofAHCtxDiusWO8ZBmxsbkRGJeF5GDOHc7nd9psIM7WdO9Bbv2xPdQbJ50sPvrIhHG1Gkg7EEoMCK3TQx4AUSG32dX+D6RjF7XGKW8p7iE0bb45pqxEbjLE2ZoqA/3FJPQ9Ff4Yuy8S35JH2mALM7APCbd2s7pgWvanErAGOZKtp7CwAXmLafXMbTu/NozK0OrcJ1/JE+223/cHkVYttnwZkTTGR2HYyZ2CbbQ4QpOXAkfpL3yzG2YYXNTFYqt08hFxExws5w=,iv:vSi6/vprsRfMy4gyA0I26Sl9gXhlj5qguKC9ox9RcMs=,tag:OyuJhxfKKoc0YmB88LJtLg==,type:str]
        work: ENC[AES256_GCM,data:zHa2sQGBMU9pa1+ty10R3BrIR0WMou7aA58p7NT8bABKWXRNT1PxLK4xiwRkoThyQyeCvLANHVbOi7QIAQY0Wm0VpqveCyLcmMnCf6dmDfvq0bKPddKN9NkI/1pZLby51M29uldC2IH71HykUjTQUh72476BoviLoz4PUP4AqDA/7FoJSLZXFwJZk8c0CrmWOQ2gqhyuMY6t5a6Z/6O+6mluwplcifiWMMU=,iv:uVsFp5V+P9li8Dg8LgxusmygITNdoqxfsEFQAoCICqg=,tag:6KgYGhooIHU0Nhc1fQt8mw==,type:str]
        extras: ENC[AES256_GCM,data:SEMkQ+nZsNanCPIsm2JNu9SBdO0LJw8XENFEyOIn35ItMbClN2z98lmnnKdvWLIxbeOK31qZ1P7lp/BgSCCdO/3/nJlX0TZdFDS2VbboRjxrGqxdCu7EBcAx8P+6QPoFwJnU4LOmAU4PNbA2KdIOvGynnC/GWpW/Df9tE3W/PFDNEvCRlwX0PI7wTPoDgzdBD4Q8+Ev3P86TL+Wq+mNGGjSqjW8bYjnHt2B+KQ==,iv:r6tCYx6QhpbGEYFlyCq/4pmg/jIa5bZ4p2WQjHUvQIc=,tag:Mterprzohi3ANE4ncwrf6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z3sn5lc7dn4cwwar29dy7yl9zqqygdunds42nw8rm9lh5adgyu3s2ll05r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXR0ZKNFZxRWtnT3FlcWo0
            L0xWVWdmQUtrQS9LZUZDWk5GWk5XVENRdWhRCnZSckhhSTNNbUtjUDh0VjczRjV6
            WEw5QVp0WWJPMHdYaGxBb093bzgrY2MKLS0tIHpwdVhPdVVGSXhsNXhJTit2ZCtS
            TmRmWUlFZm1FRHcwVjFlL1RvQVVPLzgKvl4f5I8EQCp0Yf2kgPLifXGrD/HaH9/p
            sBpwiZSmplR8f3daDYgxS4wnaZ7pJYjGQfPreyDtgXl5s1XS5+m00Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-08T13:10:04Z"
    mac: ENC[AES256_GCM,data:JpGp+Ahz4LNMcVyfM3TdF/A72fUhaIDitTQccVYxoCg3S4/I3/cp/DXVbyVNoq4xAmE3eT/bUVyRY3QKdmgTZKSKnrmtFeZPDE5C9+PwO4sVtbcgB3Am4k2ow2lhQ6BUxLh0iXt97iMHYyOAXRUitg0fL8Qxoi8k8uDB9j0+w/k=,iv:/Vp9eMg2d1ldoC+8bTxu19UB80eTzrE26SM7voktO/Q=,tag:aI8mXlZuXE7ihAlYVW1o7g==,type:str]
    pgp:
        - created_at: "2024-02-08T13:05:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAzVskl6rsqh0AQ//Y+PwH0iMrCoBJQV7Ri1f/zMaCPWbBkiGgrrFSg68R6If
            +SAFRKwKtNm5kS7udzAldNmes7vFhUzKzuvwExyYBdOtaTDNStApYNoTlHFi9AZI
            H/244U1Ev/G7Tx2w632ubOn5odO+LFixTC+sen/v31seMJr34aJdBoBMgxMeJgik
            mhxETQgBiUw4GkC8rgvByQy+ORm3SG8H202Ub675FqvDBtE8IqdY3sKTyzy8ooxU
            6C3lqWSkPFzkKnwxS4oX7ASFJuY/kAJGncbrx3UV+igC4vBWOFSfnNfq3s4qw37g
            wcm9caSZfKy1JQSM+VKNEyaZe3jS6dSqk3WnSuF+vXbwBWRJe7uvMXY2lw9k7EUL
            VqdO54pAaNmZoGGsnzwb1Bta7phGRNQtj+4TIfFCKflComa1FzshOWMlpsWotTP/
            65ce++CH1WgoxK0+2lanrXCtpTZNoBpqdfhjCBjsD7ZMIni1suvMImBOYjrnA2Mo
            XEMi2z3XvDNAiyS1CNed45bOmMZ7pryyp8eSWFEWGSvvP0xTbz000vHBBdkputZC
            qKXEi1f2576RfW9lqOw9Mdl7rHKg+jefuePHOrrfW7BET50IQ+sPS/Du8kJvTQRO
            L1XweKJ7HgnnRlM3pyoNBnAtdxx+X2nsm87Ib4b5rOjCgjMAbERYb0vBagfFkiPS
            XgFJzn9OFDagl9AzyBAMay1ror2DGRIi73idnICioZrDOiohXTKIR0rzNOjJ/Ubb
            S1ayJcRIyxMq293+yJLuHOBhBNL81TpXa8JAaDu5AT7yCPM+L+vhhHJJLxzydSs=
            =sT6E
            -----END PGP MESSAGE-----
          fp: B08FE2644F9FC450AF425FF5B94F394B72884017
        - created_at: "2024-02-08T13:05:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0Q28yf+m+BrAQ/7BQmAZQWTmleqSP2YxxohyYKt9poTpGzqfFT7obo6nXWH
            KSlZ6Zrj6PADlfCUFv1vZ/qknX/UgkO6B3uMaMtMUcZqB5XgR1DdGg5Pyq8+SUSh
            7YOsaXuWYr69G7eRfHSVj9Wt78K+7cl+2vHo9gPRhBU6Lo82ZGRBeXVm12qjr/Ep
            f6GBG0NnIj2D3KmbccvMFFnmPsDvdDePgK2tqt8BQWdU57vR9mFTjq2/9vLeZydF
            oedwSo3zsO6YdtCilM8aRwU5Zu3RkHMKH6Lad0MGnWf3hW8FR8IVZpij7onEAITv
            RiSrDUyqlMGdATM7PxncIhv2h+c+qVcvN2faLFbvW3dfuPyndfmLThtrTG4rDe6Y
            kLVNu8G7pT3dn1yQYKcSXtFNrzAKaowQ1Qa7bpFIOIYiUMRsStbYfJDewtW5QtK7
            hQgKoi4RrKegrXw00Udd0KD+tn2yLH29KiF62bZPoC0BcM+vMpRmBVMZbyPY+BOH
            JXUA7rPv9V3kVFDIUeBbXwFaMi8BQqX189DcRvu1PSY1Eh6paQypQqA3JcqVx50e
            /pVU39ESY1sFVmSOiGwihiqWjjceBSJWnKmsTjYpQjqHrfBHY2vfTPh6UtH2iqCP
            B57AAtHpCifSCf3k1Jj5N20uCZcm1F+bDmHiYr/Sr2FeEId/rAaBO8OOa//7IIaF
            AgwDlo4O5o7M6KgBEACYa9znBEeviR54JoQwya9iycP2Q4chEEPy3gs2WCMyinEq
            Mv6cMQ2RalN0pR8SOokL3zYU6TlglQnDuo2hIrAg3Os2dwH4QV7EKdGfzI1YoUcq
            K4IOSWKpjfr/k54SgE4qclZ9fZF+86AatJ70TKXhhvVLxTN3zg1NbmMQzjmPX/pf
            XMEa6t4K4JAGqB9Um8OV+q/8aPvqmrx5wCZV6DI1lC/xeZR+k/sQctj/o4UnSUac
            MLO9SgOHUseZdKc51LaN53AEh20TldIGZLt+kAEE+ryNf8MitS6k5PMgIl0VByLs
            Av49wc0z4k4vCTmR/dRpO5zXjYlOTgmSRqA8qJZ/WF660B73HY3mQMGHvbFv7oRh
            NpuLylsddG5QRKdg9M63Tk4gch4CVI7RAQkiY0lxIVEj67nPkl56+gmZWP1IVNYL
            EBr5IbWK3n3ztvZQ2qpokORtwpjaEk0buUqX5RKFpGfiA8hHg/lNnopQQEyuAaIU
            ixRrEE9UYeAKaWVtMH8j/X9tMr/03HivKkgUfcAgeSLKMdz/TBd1N72o+RrqhVeV
            ycj5pdEE8hZlVshtOWcfqS0oCrtE8JK7tqkVASATAoAd69H2sgW4OZDFSyNnF7BO
            I5fSaVGDnuBsvxllh+MkBT4hjNnK3NYwmm74YIkfTTQfep7MmPr3Zhb+8MpmYNRo
            AQkCENLwXlaE45PZeYYDOu1aARO3Dhu9FsoRYKrlL34W7xWNi4ecufMeSZ5gkK+z
            eX6kUTY8FSoCzzC62Mi14sCVCxcb0sjcZTUaMZzl3uFmcPwnJ+dktnTvEYLYAty3
            Uf9xm6RcalM=
            =YCbX
            -----END PGP MESSAGE-----
          fp: 5825C9F026638FF69FDC278DEA5A11F2DDC77EF1
    unencrypted_suffix: _unencrypted
    version: 3.8.1
